### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by JonnyBGod** [jonathan-casarrubias/loopback-component-pubsub#2]
How is the library scaling to multiple server instances?

**Comment by jonathan-casarrubias** [comment]
hey @JonnyBGod good to see you here also!!! I already have the solution but I have not implemented yet.. this is going to scale using socket-io adapters.

I already implemented all of this in a project I built last year, but since I have been putting a lot of effort on the sdk builder, I have been supporting only bugs.. If the builder seems to be stable enough during this week I will implement the clustering feature : ).

Cheers,
Jon

**Comment by JonnyBGod** [comment]
I would love to have support for different queues (if thats your way to go) normally I see a lot of people using redis for these scalability problems. But I actually prefer to have more options like nat.io, kafka...

**Comment by jonathan-casarrubias** [comment]
I have used the adapter with mongodb since it has built in pubsub module that allows this functionality to scale, So... I'm pretty sure I will implement it as a configuration in order to select an adapter (redis, mongo), I like to keep things centralized within the loopback framework.

But giving a quick look at kafka I think we can also support a way to send messages to kafka  by  also adding a configuration and maybe -not sure- a combination could create a really powerful platform in terms of scalability for huge traffic systems.

Also this second option you propose can allow users using mysql and sql server to implement this functionality, since this component won't scale for those who use a sql db which I usually don't support that much, so I agree is a great option to implement. 

At the end, my idea is to provide a configuration interface to allow devs to select any of these.

Cheers,
Jon!!!

**Comment by jonathan-casarrubias** [comment]
Implemented Clustering functionality on release 1.0.18

The current implementation uses adapters, but could be extended to use something like kafka.

Closing for now
