### ISSUE TITLE
Usage with Nginx and Strongloop Process Manager

### ISSUE THREAD

**Issue by dmastag** [jonathan-casarrubias/loopback-component-pubsub#9]
Just read about this & the [lookback-sdk-builder](https://github.com/mean-expert-official/loopback-sdk-builder)  and it looks absolutely awesome. 

Quick question, I am currently developing locally with a plan to use Nginx & Strongloop Process Manager once going to Production. I don't have the production environment ready for a couple of weeks so I can't test this for myself.

Will this work with my planned setup?

Thanks and keep rocking!
Julian

**Comment by jonathan-casarrubias** [comment]
Hi @dmastag 

Thanks for for your nice words!!! also this setup definitely works with one condition, you will need to use a PubSub capable database like mongo or redis if you are willing to scale.

Why? because this is the only way to scale between many processes and server instances when enabling clustering environments.

If you really need to use a SQL database to persist your models, you will need to setup a MongoDB or Redis only in order to enable the clustering functionality and let the SQL datasource for models persistance, but I do not recommend it.

cheers!!
Jon

**Comment by dmastag** [comment]
Hi @jonathan-casarrubias ,
Honestly I didn't even know pubsub capable database was a thing before you mentioned it and have been reading through some stuff. Well I am using MariaDB in my setup, does this mean there is no way I can implement realtime web sockets. 

I know now that this might be out of topic but I was looking at [angular-livesets](https://github.com/strongloop/angular-live-set) but it is sadly still in angularJs.

Thanks
Julian

**Comment by jonathan-casarrubias** [comment]
@dmastag yes you can setup your app using mariadb and still use the pubsub functionality from this component I maintain.

The issue comes when you want to scale to more than 1 server or node process, you won't be able to communicate between servers to allow everyone subscribed to the same events in different servers, the only way to coordinate the events between these instances of the API is by using a PubSub capable database.

You still can use MariaDB for your models, but you will need to setup and additional MongoDB just to allow the coordination between servers/processes.

The EventSource approach is not so robust, because only works in some browsers... Still I will add support in a future version for this, but remember the following:

The SDK generated by the builder can run in multiple environments, not only in multiple browsers... that means that the EventSource is far crossplatform as the websockets

**Comment by dmastag** [comment]
@jonathan-casarrubias ok, so I basically have to learn to how to use MariaDB in conjunction with MongoDB for the pubsub to work in the production setup I have planned. Honestly I am a bit afraid imagining that maintaining both could become a nightmare later on (which is why I tried to look at [PubSubSQL](http://pubsubsql.com/) which has sadly no development the past 5 months). But lets see if I can make it.

Should I create a new Issue for the EventSource Implementation?

Thanks for taking the time to answer my questions.
Julian

**Comment by jonathan-casarrubias** [comment]
@dmastag there is already an issue in the sdk builder repo for the EventSource support, it should not be in this repo since pub sub and event source are different, but both will be supported by the sdk builder.

If you create a MongoDB / Redis instance and you set the credentials to the pubsub cluster configuration; then it directly passes that to the socket.io mongo db/redis  adapter, and socket.io then handles anything in that database for you.

So you will need to make sure there is a socket.io-adapter for the selected database in order to scale.

I have to be honest, SQL databases are old technologies and they are a pain... A year ago I had a client that requested to build a chat and I use a primitive version of this modules, we developed in mongodb but in production it was pointing to mysql and was slow and unreliable in comparison of dev or staging using MongoDB, the performance diff is notable.

Anyways these are just experiences I wanted to share with you.. Sometimes in some projects there are not options, so If you can sell the idea is great, otherwise will work and if you are used to SQL performance, then you may not even see the difference..

Cheers!
Jon

**Comment by dmastag** [comment]
@jonathan-casarrubias thanks for the explanation on the EventSource support. Sound promising and I will keep an eye on any updates.

Currently I have quite limited experience with NoSQL which consists of using Parse and Firebase. Hard to put your head around it after years of using SQL. I think I can implement NoSQL on Social Features like Chat and Feed, but for an accounting system or hr System ... I can't really imagine porting a whole app to NoSQL. Maybe its just my limited experience in the field :smile: 

Julian

**Comment by jonathan-casarrubias** [comment]
@dmastag yes that actually make sense, fortunately LoopBack allows to set varied set of datasources, as you say you can set a SQL database to the not realtime functionality and use NoSQL to others models regarding to Chats, Notifications, etc. And with loopback you can even create relationships between models with different datasources, so it sounds like a good plan.

One step at the time

Cheers!
Jon

**Comment by jonathan-casarrubias** [comment]
https://github.com/mean-expert-official/loopback-sdk-builder/issues/84

**Comment by dmastag** [comment]
@jonathan-casarrubias the relationships from Loopback that is independent of the datasource is the main reason why i have loved it. Am closing this issue now and will look into [mean-expert-official/loopback-sdk-builder/issues/84](https://github.com/mean-expert-official/loopback-sdk-builder/issues/84).

Thanks for the support
Julian
